### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by candrews** [kodi-pvr/pvr.vdr.vnsi#100]
According to https://github.com/kodi-pvr/pvr.vdr.vnsi/blob/Krypton/pvr.vdr.vnsi/addon.xml.in, the current version is 2.6.14. Can you please tag this release?

Releases make things a lot easier for distributions (in my case, Gentoo) to package the add-on.

Thanks!

**Comment by FernetMenta** [comment]
Krypton is not released yet.

**Comment by candrews** [comment]
> Krypton is not released yet.

It is now - https://github.com/xbmc/xbmc/releases/tag/17.0-Krypton

**Comment by FernetMenta** [comment]
done https://github.com/kodi-pvr/pvr.vdr.vnsi/releases
