### ISSUE TITLE
For "some reason" my Jarvis Kodi doesn't connect the first time to VNSI server (Maybe problem caused by hostname resolving to IPv6 address)

### ISSUE THREAD

**Issue by M-Reimer** [kodi-pvr/pvr.vdr.vnsi#102]
I tried latest VNSI server plugin (1.5.1) with the latest GIT version for the Kodi Addon in the Jarvis branch. What I get are the error messages at the end of this bug report. It seems like Kodi tries several times without success but for some reason finally successfully connects.
I've downgraded to 1.5.0 now and at least for now it seems like I get a connection immediately again with every try.
Does the Jarvis branch need some (minor?) update to work flawlessly with the 1.5.1 version of the VDR plugin?
Thanks in advance.
EDIT: Got the same problem again with 1.5.0... :( I really don't know why this happens. There are two clients. One directly on the VDR machine (connecting to localhost) and a second Kodi instance on my desktop. The "local version" connects immediately, my remote version sometimes shows the described problem...

12:23:19 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:19 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:19 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:23:24 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:24 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:24 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:23:30 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:30 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:30 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:23:36 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:36 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:36 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:23:42 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:42 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:42 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:23:48 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:48 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:48 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:23:54 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:23:54 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:23:54 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:24:00 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:24:00 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:24:00 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:24:06 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:24:06 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:24:06 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:24:12 T:139720814208768   ERROR: AddOnLog: VDR VNSI Client: Open - failed to connect to the backend (Connection refused)
12:24:12 T:139720814208768   ERROR: ADDON: Dll VDR VNSI Client - Client returned bad status (1) from Create and is not usable
12:24:12 T:139720814208768 WARNING: UpdateAndInitialiseClients - failed to create add-on VDR VNSI Client, status = 1
12:24:14 T:139720814208768  NOTICE: AddOnLog: VDR VNSI Client: Logged in at '1485001454+3600' to 'VDR-Network-Streaming-Interface (VNSI) Server' Version: '1.5.1' with protocol version '9'
12:24:14 T:139720814208768 WARNING: GetAddonProperties - Addon VDR-Network-Streaming-Interface (VNSI) Server:manuelsvdr:34890 does not support timer types. It will work, but not benefit from the timer features introduced with PVR Addon API 2.0.0
12:24:15 T:139720856172288  NOTICE: Start - EPG thread started

**Comment by FernetMenta** [comment]
vnsiserver 1.5.2 should have this fixed: https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/c0e68013d94301e560af96a43cab99964dd52c87

**Comment by M-Reimer** [comment]
Oh. I'm sorry that I missed that one. Thanks for the update!
I will test again with this updated version and report back if I still have the described problem.

**Comment by M-Reimer** [comment]
Problem still exists... May it be possible that this has something to do with my migration from dhcpcd to networkd?
The problem is completely gone if I enter the IP of the VDR server.
The problem keeps happening if I enter the hostname.
The interesting thing is that the VDR side logs doesn't show any connection attempts, but my guess is that maybe for some reason Kodi tries to connect via IPv6?

**Comment by FernetMenta** [comment]
> May it be possible that this has something to do with my migration from dhcpcd to networkd?

could be but not sure how. kodi side vnsi addon uses pulse-eight lib to connect to the backend. if you are on Linux, this results in system calls like getaddrinfo:
https://github.com/Pulse-Eight/platform/blob/master/src/posix/os-socket.h#L283
if I am not mistaken, this should work with ipv6. do you have a chance to log addinfo in that call?

**Comment by M-Reimer** [comment]
But maybe Kodi or some other involved code part doesn't support ipv6?
I could log stuff. Just have to rebuild the involved library for this. What exactly do you need?
I have a very old router which doesn't support ipv6 at all and I have tried to disable ipv6 wherever possible in my networkd configuration but somehow the two linux systems still connect using ipv6. If I ping the VDR server from my desktop PC, then the IPv6 address is displayed. I don't know what kind if IPv6 magic the two linux systems are doing here...

**Comment by M-Reimer** [comment]
Maybe I have it just by using "strace". This is what I get for the connection attempts if I have the hostname set (much more of them. I just paste the first few lines:


 1780  connect(67, {sa_family=AF_INET6, sin6_port=htons(34890), inet_pton(AF_INET6, "fe80::922b:34ff:fea7:5f7f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=if_nametoindex("enp3s0")}, 28) = -1 EINPROGRESS (Operation now in progress)
 1780  connect(67, {sa_family=AF_INET6, sin6_port=htons(34890), inet_pton(AF_INET6, "fe80::922b:34ff:fea7:5f7f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=if_nametoindex("enp3s0")}, 28 <unfinished ...>
 1780  connect(67, {sa_family=AF_INET6, sin6_port=htons(34890), inet_pton(AF_INET6, "fe80::922b:34ff:fea7:5f7f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=if_nametoindex("enp3s0")}, 28 <unfinished ...>
 1780  connect(67, {sa_family=AF_INET6, sin6_port=htons(34890), inet_pton(AF_INET6, "fe80::922b:34ff:fea7:5f7f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=if_nametoindex("enp3s0")}, 28 <unfinished ...>
 1780  connect(67, {sa_family=AF_INET6, sin6_port=htons(34890), inet_pton(AF_INET6, "fe80::922b:34ff:fea7:5f7f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=if_nametoindex("enp3s0")}, 28 <unfinished ...>
 1780  connect(67, {sa_family=AF_INET6, sin6_port=htons(34890), inet_pton(AF_INET6, "fe80::922b:34ff:fea7:5f7f", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=if_nametoindex("enp3s0")}, 28) = -1 EINPROGRESS (Operation now in progress)


Same with directly entered IP address (just this one line):

 1929  connect(34, {sa_family=AF_INET, sin_port=htons(34890), sin_addr=inet_addr("192.168.178.122")}, 16 <unfinished ...>

If I ping the address, then everything seems OK:
 $ ping -I enp3s0 -6 'fe80::922b:34ff:fea7:5f7f'
 PING fe80::922b:34ff:fea7:5f7f(fe80::922b:34ff:fea7:5f7f) from fe80::922b:34ff:fe96:120f%enp3s0 enp3s0: 56 data bytes
 64 bytes from fe80::922b:34ff:fea7:5f7f%enp3s0: icmp_seq=1 ttl=64 time=0.200 ms
 64 bytes from fe80::922b:34ff:fea7:5f7f%enp3s0: icmp_seq=2 ttl=64 time=0.257 ms
 64 bytes from fe80::922b:34ff:fea7:5f7f%enp3s0: icmp_seq=3 ttl=64 time=0.187 ms
 64 bytes from fe80::922b:34ff:fea7:5f7f%enp3s0: icmp_seq=4 ttl=64 time=0.182 ms

**Comment by FernetMenta** [comment]
looks like getaddrinfo does not return an addrinfo structure for v4. (vnsiserver only accepts v4, I have never touched this code so far)

**Comment by M-Reimer** [comment]
I'm not 100% sure if my setup is actually a valid ipv6 test case (as mentioned my plan was to disable ipv6) but as I'm able to ping this "somehow magically assigned IPv6 IP" (DHCP server clearly isn't able to do this. Far too old) I think IPv6 connectivity at least in theory is OK.
I can live with the fact that now, as networkd assigned IPv6 addresses without asking me, I have to use the IP and not the hostname, but maybe this gets more problematic in future. For example first ISP's in germany assign IPv6 public addresses only. IPv4 only via some kind of proxy.

**Comment by M-Reimer** [comment]
Just in case someone get the same problem:
https://coreos.com/os/docs/latest/network-config-with-networkd.html#turn-off-ipv6-on-specific-interfaces
Doesn't solve the IPv6 problem but makes it possible to disable IPv6 if networkd is used.

**Comment by Jalle19** [comment]
The `fe80` IPv6 addresses you see are so called link-local addresses. Every IPv6-capable node on the network will automatically assign one of these addresses to each interface. What I suspect is going on is that your server doesn't listen for IPv6 connections at all.

**Comment by FernetMenta** [comment]
@Jalle19 I already mentioned that the server does not listen to v6 but the client should connect to v4 then, right?

**Comment by M-Reimer** [comment]
It does after some time... Otherwise I wouldn't get a working connection after some waiting and many failed attempts.
I don't know if there are any ways to force IPv4 connections. If the VDR plugin isn't able to handle IPv6 connections it would be the best if the Kodi client doesn't even try with IPv6.

**Comment by Jalle19** [comment]
@FernetMenta AFAIK IPv6 is always tried first, but I don't know if that's the case if only a link-local address is available.

Obviously the most proper solution would be to make the server IPv6 capable.

**Comment by FernetMenta** [comment]
I agree, that's probably less effort than changing pulse-eight to allow forcing v4

**Comment by AlwinEsch** [comment]
Issue closed.

System now done by kissnet and if problems present a new issue needed!
