### ISSUE TITLE
"Any channel" timer rule is not working

### ISSUE THREAD

**Issue by bgmvdr** [kodi-pvr/pvr.vdr.vnsi#107]
When creating a new epg search timer rule with "Any channel" selected it will not be saved.

**Comment by FernetMenta** [comment]
The issue is on kodi side because it displays "any channel". The plugin does not support this.

**Comment by FernetMenta** [comment]
I already requested a some means to suppresss this.

**Comment by ksooo** [comment]
I have the pvr core support for this on my list for Kodi Leia. Once it's done the add-on can be "fixed".

**Comment by FernetMenta** [comment]
Thanks muuch @ksooo

**Comment by bgmvdr** [comment]
Thank you for doing all this great work here!
