### ISSUE TITLE
libXBMC_codec.h removed in Kodi 18

### ISSUE THREAD

**Issue by StormTrooper** [kodi-pvr/pvr.vdr.vnsi#111]
Build is failing with latest v18. 

> In file included from /mnt/package/mediacenter-next-osmc/src/xbmc-35925be7ff4e9ee911387a873f7c01387f3a38ee/cmake/addons/build/pvr.vdr.vnsi/src/client.cpp:22:0:
> /mnt/package/mediacenter-next-osmc/src/xbmc-35925be7ff4e9ee911387a873f7c01387f3a38ee/cmake/addons/build/pvr.vdr.vnsi/src/client.h:24:27: fatal error: libXBMC_codec.h: No such file or directory
>  #include "libXBMC_codec.h"
>                            ^
> compilation terminated.
> CMakeFiles/pvr.vdr.vnsi.dir/build.make:134: recipe for target 'CMakeFiles/pvr.vdr.vnsi.dir/src/client.cpp.o' failed
> make[5]: *** [CMakeFiles/pvr.vdr.vnsi.dir/src/client.cpp.o] Error 1

libXBMC_codec.h has now been removed with this commit:

[pvr] remove libXBMC_codec.h and add to libXBMC_pvr.h
https://github.com/xbmc/xbmc/commit/979c3305027c76b0cf9add54a0cf0ae05d0fe3e6

**Comment by AlwinEsch** [comment]
The repo becomes handled direct since begin of the year by FernetMenta (https://github.com/fernetmenta/pvr.vdr.vnsi).

Have created a request https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/112 to have it sync with them

**Comment by FernetMenta** [comment]
this repo is dead. i removed master branch to make that clear

**Comment by StormTrooper** [comment]
Thanks.  Will point to https://github.com/fernetmenta/pvr.vdr.vnsi

**Comment by AlwinEsch** [comment]
This done long time ago and issue can be closed.
