### ISSUE TITLE
Wakeup script no longer called at all. PC doesn't wake up for recordings...

### ISSUE THREAD

**Issue by M-Reimer** [kodi-pvr/pvr.vdr.vnsi#113]
I'm running Kodi 17.1. I currently use the following GIT version of the VNSI Kodi addon:
2a90c2f9a1f3e5889336a8df5426ff99b0318b0f
The Kodi GUI shows me that there is a recording pending some days in future.
I've added some logging to my wakeup script so I know when it is called and with which parameters.
With the pending recording and the "modified" wakup script, I used the Kodi-builtin shutdown function to shut down the system. Result is, that the wakeup script isn't called at all. I don't have anything about this in the Kodi log files... Is there some way to debug this and to get it working again?

**Comment by M-Reimer** [comment]
I've updated everything (VDR Plugin and VNSI Kodi Addon) to the latest GIT version now.
Still no sign of calling the wakeup script. No errors or anything, not in the Kodi log file (debug log enabled) and not in the system log.
Will be busy until the next weekend. If possible, please give some hints on how to find the reason for this problem so I can provide more information next weekend.

**Comment by FernetMenta** [comment]
what wakeup script are you referring to? vnsi has no such feature nor there is any PVR api for this.

**Comment by ksooo** [comment]
This is a kodi core issue that will be fixed with Kodi 17.2

**Comment by ksooo** [comment]
=> https://trac.kodi.tv/ticket/17374

**Comment by M-Reimer** [comment]
Thank you for the link. I didn't know where the "wakeup"-Feature belongs to. So if this is part of the kodi core, I'll close this one. Are there any plans when Kodi 17.2 will be published?
