### ISSUE TITLE
Recording playback progress no longer stored across sessions since Kodi 19

### ISSUE THREAD

**Issue by M-Reimer** [kodi-pvr/pvr.vdr.vnsi#142]
I don't know if this is a generic PVR issue (if so, please link the Issue here) but since updating to Kodi 19 the progress of already watched recordings does no longer survive a reboot.

Was there any change in the PVR API which requires a change in the PVR VDR VNSI Addon?

**Comment by phunkyfish** [comment]
There were a lot of changes as the add-on moved to the new C++ API for v19. But afraid I'm not familiar enough with this add-on to know exactly how/if it would impact the add-on in that way.

There are some new API introduced that allow for storing playback progress/count on the backend. But I think they came in before V19.

**Comment by ksooo** [comment]
> But I think they came in before V19.

 Right.

**Comment by phunkyfish** [comment]
Am I correct in saying that for recordings progress should be stored through reboots in the video library? I feel like it worked that way at some point.

**Comment by M-Reimer** [comment]
I think so. The concept of VDR to save the last playback position is a "resume" file which is missing in all my recordings. So I think Kodi itself saved the state.

Directly when updating from Kodi 18 to Kodi 19 all my progress in Amazon Prime Video was lost, too, but recently watched movies in Kodi 19 survive a reboot, now.

**Comment by M-Reimer** [comment]
This issue seems to be fixed by this Kodi PR: https://github.com/xbmc/xbmc/pull/19451
Verified here: https://www.vdr-portal.de/forum/index.php?thread/134273-kodi-19-und-pvdr-vnsi-probleme/&postID=1338085#post1338085
