### ISSUE TITLE
compiling on imx6/gpu-viv

### ISSUE THREAD

**Issue by mk01** [kodi-pvr/pvr.vdr.vnsi#22]
when vnsi is being configured, according it's cmake file it looks first for OpenGL.

imx libs do contain libGL.so, but this is used for X and whole configuration / compilation goes wrong direction.

**Comment by wsnipex** [comment]
the question is how we can identify imx in cmake.

**Comment by mk01** [comment]
@wsnipex 

we follow the existing approach via configure.ac (on mxcfb.h have_imxfb is set), then in m4/xbmc_arch.m4 set ARCH_DEFINES to the usual plus -DTARGET_IMXFB

this is finally stored in kodi-config.cmake.

**Comment by wsnipex** [comment]
whats the usual way to compile kodi for imx? Just unified depends or also native standalone build on the device itself?
In the former case we'd better add something like https://github.com/xbmc/xbmc/blob/master/tools/depends/configure.ac#L303 for IMX as well. And then here: https://github.com/xbmc/xbmc/blob/master/tools/depends/target/Toolchain_binaddons.cmake.in#L17

If you need standalone native compile, then we can only add it to kodi-config.cmake, but preprocessor defines won't work, it needs to be a cmake var.

**Comment by mk01** [comment]
@wsnipex 

I can't speak for all distribution builders but I assume the general case is unified depend.
Still, I can imagine users wanting to go ahead of distro packages or whatsoever experiments.

If preprocessor defines do not work with CMake like this, then let's save the have_imxfb as use_platform=imxfb, then load this into PLATFORM variable as you showed me for RBP and store this also into kodi-config.cmake. 

this would be possible ?

**Comment by mk01** [comment]
@wsnipex 

or maybe most universal would be to pass (from kodi configure/compile setup) whether used system was  GL / GLES2 / W32 / OSx.
it would make the auto-configuration easier. just tests would be needed for actual lib presence, but the guessing what to check would be gone.

**Comment by wsnipex** [comment]
that doesn't work as unified depends build addons before kodi, so no info from kodis configure is available at addon build time. You would have to duplicate all that in depends configure.

**Comment by mk01** [comment]
@wsnipex 

sure, "depends". :)) i'm skipping words when reading sometimes. this is out of scope - we build fully on top of binary distribution(s) - so kodi is build against prepared environment. ....

for the time being until this works auto, is there a way to locally adapt the cmakeiists file, that running compilation process won't revert it back (probably by updating repo files)?

I run cmake, then change the file, then make, and it gets restored on the fly .

**Comment by wsnipex** [comment]
since you are building on a distro, you should follow the standard linux packaging workflow:
http://forum.kodi.tv/showthread.php?tid=232318&pid=2054777#pid2054777
in that case you can change the repo however you want.

**Comment by mk01** [comment]
@wsnipex 

so there is no option/cmake variable to disable the auto update step?
I just wanted to avoid spending time writing additional scripting on top of already auto building tree.

**Comment by wsnipex** [comment]
which auto update step? Guess I still don't understand what your build workflow is.

**Comment by mk01** [comment]
@wsnipex 

docs/README.linux
section 4.4. Binary addons - compile

**Comment by stefansaraev** [comment]
my w cents on this:

if you dont use/need x11. you should not install libGL.so to your (cross?) toolchain.

here is what we do in openelec
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/graphics/gpu-viv-bin-mx6q/package.mk#L50-L63

^^ so GLESv2 is detected and used.

**Comment by mk01** [comment]
@wsnipex 

changed project/cmake/addons/addons/pvr.vdr.vnsi/pvr.vdr.vnsi.txt  to point to local archive. so it builds in one run nicely now.

**Comment by mk01** [comment]
@wsnipex 

a bit inspiration - see https://github.com/kodi-pvr/pvr.vdr.vnsi/pull/23 ... this looks to cover all the possible variants (specially in case of native compilation on device itself (which also might have X/Mesa etc installed).

maybe we find some variant which is acceptable and works on full scale of systems supported by default by Kodi.

**Comment by mk01** [comment]
should have been closed long ago. doing now.
