### ISSUE TITLE
Channels not displayed when using the proper picons path

### ISSUE THREAD

**Issue by jakubklos77** [kodi-pvr/pvr.vdr.vnsi#30]
Hello
great work on the plugin. 

I have created a simple script to generate picons symlinks (map them with proper channel png files).
I traced kodi accessing the picon files (with strace) so I knew it wasn't channel name based but picon based.

However, now I can see Kodi accesses the picon files but they are not displayed (they are transparent). Any ideas what could be wrong?

There is nothing in the kodi logs although I haven't checked with the debug mode yet.

Thank you very much

**Comment by FernetMenta** [comment]
> I have created a simple script to generate picons symlinks

why? all you need is in the picons package.

**Comment by jakubklos77** [comment]
I was not able to find the correct picon package. Anyway, I have found some picon for Thor 0.8W and it still does not work. Anything, I can do?
Thank you

**Comment by FernetMenta** [comment]
Not sure if you look in the right place. The picons site is this: https://picons.xyz/ with updated ready to use binaries for Kodi: https://picons.xyz/downloads/?dir=binaries-srp
All you need to do is to extract to a folder and point vnsi config to this folder.

**Comment by jakubklos77** [comment]
Thank you, I wasn't aware of this site. I downloaded the Kodi package and it still does not work.
I set it to the root of the folder (not the tv folder). There is no cache or something that would make Kodi ignore those files?

**Comment by FernetMenta** [comment]
make sure to clear "Folder with channel icons" in general TV settings.
what version of Kodi/vnsi/vnsiserver do you use?

**Comment by jakubklos77** [comment]
I did that and still does not work. I have even checked in the channel manager. The icon is blank.

Linux Ubuntu 14.04
Kodi 15.1
VDR 2.2.0
VNSI server 1.3.0
VNSI addon 1.10.10

**Comment by FernetMenta** [comment]
I have not released 1.3.0 of vnsiserver yet. Hence I don't know what exactly is in this version you are using. Where did you get it from? Does it include https://github.com/FernetMenta/vdr-plugin-vnsiserver/commit/017c1b0871f780c3fda946e54c12effda9cf39c5

**Comment by jakubklos77** [comment]
Must be compiled from the Git then.
I am using ppa:yavdr/unstable-vdr as it was the only thing that I got working
I can compile any vnsiserver myself though (like I did for the dvbapi and satip plugins)
However, this seems like a client issue

**Comment by jakubklos77** [comment]
I got an idea to check into Kodi's TV db. I can see the path there and identify that the last hex number (before 0-0-0) differs from the actual picon file. That's why it does not work. Could be related to the patch you sent. I will check

**Comment by jakubklos77** [comment]
Bingo, after changing my script to enforce the hash in the filename to E060000 it all works fine
Could be the fix you made though. Luckily I wrote my script so I am able to fix this.
Please, let me know. Thank you very much for your help...

**Comment by FernetMenta** [comment]
for reference: https://github.com/FernetMenta/vdr-plugin-vnsiserver/issues/26
I just released 1.3.1 of vnsiserver in order to avoid further confusion

**Comment by FernetMenta** [comment]
btw: E060000 is for 1.0 W. didn't you mention 0.8 W?

**Comment by jakubklos77** [comment]
Thank you very much
Well, probably yes. 1.0W and 0.8W is quite close so people tend to mix these (including me)

**Comment by FernetMenta** [comment]
can we close this issue?

**Comment by jakubklos77** [comment]
Absolutely. I can get it working anytime now.
The strange thing is that the picon package simply does  not contain my channels. I have tried to find 4 of them and none I could find. It is not the hash is different but even the whole channel id is missing. Not your problem though. You can close the issue.
Thank you again

Something unrelated to this issue though. I could not get the plugin working in Kodi unless I set the Priority to 15 (default was -1). Otherwise the server would simply disconnect the attempt. Any ideas? Just checking.

**Comment by FernetMenta** [comment]
Seems that some other plugin occupies the device if you need a prio of 15. What other vdr plugins do you have loaded?

**Comment by jakubklos77** [comment]
Ok, my bad. It was when I started playing with VDR and I had the xineliboutput plugin installed. It is not there now and it works even with priority -1. Glad it makes sense though

Thank you again. Great job.
