### ISSUE TITLE
README.md is missing!?

### ISSUE THREAD

**Issue by kanalja** [kodi-pvr/pvr.vdr.vnsi#36]
I can't know how to install this software and what is it requirements. Please add README.md file.

**Comment by AlwinEsch** [comment]
I can do this for Linux and try on Windows. What is your OS then I start with them?

**Comment by AlwinEsch** [comment]
@FernetMenta I add then also the licence file for the add-on.

**Comment by kanalja** [comment]
I'm using Linux (Kubuntu 15.10).

**Comment by FernetMenta** [comment]
@AlwinEsch thanks

**Comment by AlwinEsch** [comment]
Have started there, the easiest way for linux with kodi source available added.
https://github.com/AlwinEsch/pvr.vdr.vnsi/tree/add-readme

Checking now about the download of kodi source and to handle the different release branches with add-on.

**Comment by FernetMenta** [comment]
looks good
