### ISSUE TITLE
Let show "TV" in Kodi even with zero channels

### ISSUE THREAD

**Issue by the-dreamer** [kodi-pvr/pvr.vdr.vnsi#38]
Last weekend channels.conf gone empty. it took me more than one our to realize this. No error from VDR. No Error from VNSI itself. TV doesn't came up. After looking line for line in debug log i saw loading 0 groups/channel. 

If TV cannot be showed because of empty tv list maybe vnsi should at least give an error on screen that there are no channels to show.

**Comment by Jalle19** [comment]
I agree, but this is unrelated to this addon and shouldn't be reported here.
