### ISSUE TITLE
Openelec 6.0.0 VNSI PVR Addon further active PVR addon

### ISSUE THREAD

**Issue by Falcon66** [kodi-pvr/pvr.vdr.vnsi#47]
Hello,

I have activated VNSI and VU+/Enigma PVR addon under Openelec 6.0.0. 

In this case the channel groups of the VU+/Enigma PVR addon are deleted. 

Most time also the channels of the VU+/Enigma PVR addon are missing after reboot or the progress bar of the PVR manager hangs and TV is not available.

Does the PVR VNSI supports further PVR addons in parallel?

Falcon66

**Comment by FernetMenta** [comment]
@Jalle19 @xhaggi can yo answer this question?

**Comment by Jalle19** [comment]
Ancient bug, I produced a workaround that you rejected some time ago :-)

**Comment by Jalle19** [comment]
Either way it's a Kodi bug, not related to this addon.

**Comment by Falcon66** [comment]
In the past I have used the xVDR PVR addon in parallel with VU+/Enigma PVR addon under Openelec 5.0.6. (Kodi Helix) without any problems...

Is this bug already reported to the kodi maintainers?

**Comment by Jalle19** [comment]
Yes, it's been reported.
