### ISSUE TITLE
Feature request: Suspend PVR device when idle

### ISSUE THREAD

**Issue by jellysheep** [kodi-pvr/pvr.vdr.vnsi#48]
Hi there,
is there any possibility to suspend the PVR device while Kodi is in idle state?
With Kodi not running but only VDR, the PVR device is not active (not "locked"), only for EPG updates. However as long as Kodi is running, even if no TV channel is selected, the PVR device stays active and consumes a lot of power (it gets quite hot).
I couldn't find an appropriate option in the settings. Is there something I missed or is this not implemented yet?
Thanks!

**Comment by FernetMenta** [comment]
what is your definition of a "PVR device"?

**Comment by jellysheep** [comment]
With this I mean the hardware DVB-S device that is connected to the LNB and the PC (in my case, [this one](http://www.linuxtv.org/wiki/index.php/DVBSKY_S960)). It has a low power state that is activated when the device is not used (no streams or EPG searches running), but this is only the case if Kodi is not running at all.

**Comment by FernetMenta** [comment]
the only thing vnsiserver does if a client is connected is preventing vdr from shutdown due to user inactivity. vnsi only accesses the dvb device for streaming.

how should vnsi keep the device busy while not streaming?

**Comment by jellysheep** [comment]
Hi, well apparently I had a misunderstanding about how VDR works. I thought that VDR would release the DVB device/tuner (so that no channel is selected at all) when there is no receiver, and thought that Kodi / the VNSI plugin would keep VDR active.
Now I found [this thread](http://openelec.tv/forum/71-pvr-live-tv/75514-vdr-channel-locking-bug) and apparently keeping the device locked to a channel is the way VDR was designed. Now I'll try to setup the Dynamite plugin and see if its idle mode is working as expected.
Sorry for any inconvenience!

**Comment by FernetMenta** [comment]
np :)
