### ISSUE TITLE
When kodi is idle, vnsiclient should disconnect so vdr goes into idle too

### ISSUE THREAD

**Issue by simonbuehler** [kodi-pvr/pvr.vdr.vnsi#50]
Hi,

first: thanks for your great work!

My Setup:
I have a headless vdr with kodi installed on the same box (livingroom). I use the kodi Idle script addon to create a  file when kodi is idle (no tv, music or video playback) and another script takes the date and existence of this file and other services running or not into account to trigger a hibernate if its ok to do so.

The Problem is, that even if vdr would also go into idle  (and touch a file for the hibernate script) the still connected vsni client keeps the vdr from doing so.  See
 https://github.com/FernetMenta/vdr-plugin-vnsiserver/blob/master/status.c#L145

The Solution to this would be to (optionally?) disconnect the vnsiclient when kodi is going into Idle state and reconnect when User activity is detected. Then the  vdr could run its shutdown scripts(setting wakeuptimer if needed) and my hibernate script could send the box to hibernate. As Wakeup on unicast works nice, there is no problem in waking up the box from any client.

What are your thoughts on this?

**Comment by FernetMenta** [comment]
This can be done by an addon or even by an external application. Your idle script addon could just disable pvrmanager or the vnsi addon.
Personally I think there are too many components involved that raises complexity. On my living room box I observe user activity from an external little application that can shut the system down. The shutdown script queries vdr via svdrp for next timer and programs wakeup time.

**Comment by simonbuehler** [comment]
ok, i think i the solution for this is to use something like https://github.com/KenV99/service.kodi.callbacks and hooking on the idle / leave idle callbacks and send a xbmx.StopPVRManager / xbmx.StartPVRManager from there.

closing.
