### ISSUE TITLE
Channel switching from EPG display does not work

### ISSUE THREAD

**Issue by rotdrop** [kodi-pvr/pvr.vdr.vnsi#58]
Hi there,

this is with the Jarvis branch (both plugin and xbmc, of course). Compilation, installation etc. works, the plugin basically runs. However: it is not possible to switch channels. There is an Isengart related posting here:

http://forum.kodi.tv/showthread.php?tid=231303&pid=2269976#pid2269976

which suggests that setting the "priority" (whatever that may be) in the addon settings to 0. After that channel switching works (if trying to do so from the channel list). However, if I open the EPG display (timeline, so to say) it is still not possible to switch channels from there. The suggestion disable EPG-scanning during streaming (which is also suggested in the forum thread) does not change anything. I also tried to compile the master-branch of Kodi to try the master-branch of this plugin, but the compilation failed so far. I'll eventually give that another try when I have more time. 

The log show the following lines:

```
11:37:48 T:139766880249600  NOTICE: Previous line repeats 1 times.
11:37:48 T:139766880249600   ERROR: AddOnLog: VDR VNSI Client: ReadSuccess - failed with error code '997'
11:37:48 T:139766880249600   ERROR: AddOnLog: VDR VNSI Client: SwitchChannel - failed to set channel
11:37:48 T:139766880249600   ERROR: PVR - SwitchChannel - cannot switch to channel 'ProSieben' on client '741'
11:37:48 T:139766880249600   ERROR: PVRManager - PerformChannelSwitch - failed to switch to channel 'ProSieben'
11:37:48 T:139766880249600 WARNING: HandleMessages - failed to switch channel. playback stopped
```

The following remark is unrelated to the error and just explains why I'm trying to start to use vnsi, quais off-topic:
Until yesterday I was still using XBMC Frodo with the xvdr plugin and everything worked flawlessly. Just that Gentoo then decided to remove the old xbmc package. Of course, I could downgrade my HTPC to the state before yesterday by restoring  my daily backup, but that is just no fun. xvdr plugin as of now doesn't seem to be available for Kodi.

**Comment by FernetMenta** [comment]
fixed by https://github.com/xbmc/xbmc/pull/9285
