### ISSUE TITLE
Memleak in playback of recordings via vnsi

### ISSUE THREAD

**Issue by the-dreamer** [kodi-pvr/pvr.vdr.vnsi#65]
I am using OE builds from fritsch. pvr.VNSI is from now latest from git 902a3cd 
Playback of video doesn't work at all via vnsi recording. video is not started. kodi is working in background and after some minute i am back on video selection. live tv and playback a video via filesystem is working. 
http://forum.kodi.tv/showthread.php?tid=231955&pid=2281848#pid2281848
debug log
http://sprunge.us/TCDV

and picture of memory usage.
http://oi64.tinypic.com/i5vdck.jpg

if you need more info, please let me know.

**Comment by FernetMenta** [comment]
this is a mainline issue: https://github.com/xbmc/xbmc/pull/9359

**Comment by the-dreamer** [comment]
okay, didn't know, because i don't use other pvr addons for comparison. 
however, thanks for fixing!
