### ISSUE TITLE
SetAddonEnabled=false doesn't drop connection to vdr

### ISSUE THREAD

**Issue by simonbuehler** [kodi-pvr/pvr.vdr.vnsi#73]
HI,

I'm trying to migrate away from setting the PVRManager on/off to enabling/disabling the actual PVR Plugin via json rpc.
I do this in order to force he client to disconnect from the pvr server.

While the old approach worked, setting the Addon to Enabled=false does not cause a disconnect.

How can this be fixed?

```
#!/usr/bin/python
import os
import sys
import json, requests
from json import JSONEncoder


url = "http://192.168.1.100:8080/jsonrpc"

def activate(enable) :
    payload = {'jsonrpc': '2.0','method': 'Addons.SetAddonEnabled', 'params' : {'addonid': "pvr.vdr.vnsi", 'enabled': enable},'id':1}
    resp = requests.post(url=url, json=payload)
    #out = resp.text
    #print (out)

def touch(fname, times=None):
    fhandle = open(fname, 'a')
    try:
        os.utime(fname, times)
    finally:
        fhandle.close()

if str(sys.argv[1]) == "true" :
    touch("/tmp/kodiidle")
    activate(False)
    #xbmc.executebuiltin('xbmc.' + 'StopPVRManager')
else:
    try:
        os.remove("/tmp/kodiidle")
    except: 
        pass
    activate(True)
    #xbmc.executebuiltin('xbmc.' + 'StartPVRManager')
```

**Comment by FernetMenta** [comment]
I can't speak for the api but I know that it works when you disable the addon via the UI (current master branch!)
http://pastebin.com/HhhTEhjq

**Comment by simonbuehler** [comment]
ok, updated to the latest revision and getting same result: gui works but api not, don't know who's to blame

**Comment by FernetMenta** [comment]
I tried with my browser and it worked. 
http://localhost:8080/jsonrpc?request={"jsonrpc": "2.0","method": "Addons.SetAddonEnabled", "params" : {"addonid": "pvr.vdr.vnsi", "enabled":false},"id":1}

**Comment by simonbuehler** [comment]
this is strange, i'm getting the same success response in the browser or via python but the log doesn't show a pvr activity nor does the gui update (addon remains in same checked state and no "importing channels..." message, no showing/hiding of the TV Menu Entry)
:confused:

**Comment by FernetMenta** [comment]
I see the TV menu disapppearing.
Please pastebin a debug log. scenario: vnsi running, then disable via json-rpc

**Comment by simonbuehler** [comment]
I have to say sorry for wasting your time and also thanks for your help:
It works! 
A second kodi process was lingering around and caught the rpc events, but the other which was visible of course didn't react to it. Mystery solved :flushed: 

Closing ...

**Comment by FernetMenta** [comment]
np, glad that you got it working.
