### ISSUE TITLE
Bad aspect ratio of all channels

### ISSUE THREAD

**Issue by LubosD** [kodi-pvr/pvr.vdr.vnsi#75]
I use OpenELEC 5.0.3 with vdr-vnsiserver latest Git code (but also tried several older releases).

All TV channels have 1:1 aspect ratio when I select "Normal" view mode, although the XVDR plugin works OK.

I can of course force a certain ratio for some/all channels, but many channels switch aspect ratio on the fly, so this is unusable. Switching on the fly also works with XVDR, but the OpenELEC folks claim that XVDR is "obsolete" and that I should use VNSI.

**Comment by FernetMenta** [comment]
OpenELEC 5.0.3 is rather outdated and I can't do anything about it. Maybe the issue is log fixed. Please try a OE or libreELEC build with Kodi v17 and current development branch of VNSI. If the issue is still there, please pastebin a debug log.

**Comment by LubosD** [comment]
Sorry, I meant OpenELEC 6.0.3 - simply the latest stable version. But I will try the beta.

**Comment by FernetMenta** [comment]
would you have a short recording that shows the issue?

**Comment by LubosD** [comment]
I'll have the video up in a few minutes. I have checked the problem more thoroughly and the aspect ratio is probably not 1:1, but rather 4:3. Plus it only affects MPEG-2 channels, H.264 channels (no matter if SD or HD) are OK.

**Comment by LubosD** [comment]
Here it is: https://www.youtube.com/watch?v=eJqVTbfYhdQ

The first two channels are SD / MPEG-2 and have incorrect aspect ratio. It may not be so obvious from what was just playing on these channels, but they really should be 16:9. The first channel (Film+) sometimes uses 4:3, but this was a widescreen movie. The second (news) channel always uses 16:9.

This is followed by some HD channels which are correctly displayed as 16:9.

**Comment by FernetMenta** [comment]
I meant a vdr recording that I can download to reproduce the issue.

**Comment by LubosD** [comment]
Ah, sorry. Here it is: https://www.dropbox.com/s/1wrbuw0blyqrfj5/00001.ts?dl=0

**Comment by Jalle19** [comment]
Any chance you're using an AML device?

**Comment by LubosD** [comment]
AML? I don't know what that is. I use VDR with a quad tuner DVB-S2 PCIe card from TBS.

**Comment by FernetMenta** [comment]
the provided sample has a display aspect ratio of 16:9 and it shows at 16:9. what is wrong with it?

**Comment by LubosD** [comment]
When streamed from VDR to Kodi via VNSI it shows as 4:3. See at this time: https://youtu.be/eJqVTbfYhdQ?t=13s (it is the same channel)

**Comment by FernetMenta** [comment]
It shows correctly here when streamed via VNSI. Aspect ratio is set by decoder, not demuxer. What system do you run Kodi on?

**Comment by LubosD** [comment]
Raspberry Pi 2 + OpenELEC.

**Comment by LubosD** [comment]
But as I said: for some reason, it did work with xvdr.

**Comment by FernetMenta** [comment]
vnsi and ffmpeg do set the aspect ration correct to 16:9 so it must be an issue specific to Pi @popcornmix how does Pi set aspect ratio for SD.

**Comment by popcornmix** [comment]
@LubosD 
Is it better with omxplayer enabled/disabled?
Is it better with omxplayer disabled and deinterlace disabled?

@FernetMenta We use the aspect from demuxer if available, and if not from the decoder. The dropbox file does get 16:9 (seq->seq.aspect_ratio_information=3) from decoder.

There is a bug I'm aware of where changes in aspect ratio of a stream are not detected in the MMAL with deinterlace case. It correctly gets the aspect ratio at start of stream but misses changes. Enabling omxplayer or disabling deinterlace would avoid this issue (if this is the issue we are seeing).

**Comment by FernetMenta** [comment]
vnsi fires a stream change event when aspect ratio changes mid stream. this triggers reopen of decoder.

**Comment by FernetMenta** [comment]
Even if I force demuxer aspect ratio I get the correct one here.

**Comment by LubosD** [comment]
It turns out OpenELEC uses MMAL only by default (I thought it uses omxplayer). Switching to omxplayer fixes the problem. Disabling deinterlace with MMAL also fixes the AR problem.

But I disagree that "It correctly gets the aspect ratio at start of stream but misses changes". MMAL+deinterlace gets the AR wrong for me from the very beginning.

**Comment by popcornmix** [comment]
Do you ever see the issue when playing a recorded file, or only when live?

**Comment by LubosD** [comment]
Recorded as well. (Despite the playback details mentioning DAR 16:9.) But also only with MPEG-2 recordings, not with H.264.

**Comment by popcornmix** [comment]
So does the dropbox sample you posted above have the issue when played through Kodi's file browser?

**Comment by LubosD** [comment]
Yes. I've put it on an SMB share and with MMAL+deinterlace the aspect ratio is wrong too.

**Comment by popcornmix** [comment]
Not what I'm seeing on master. Video is 720x576 and aspect ratio is 1.78, resulting in video that fills the (16:9) screen. You are playing from file browser interface (and not through PVR interface)?

**Comment by LubosD** [comment]
Yes, from the file browser ("VIDEO" in main menu).

I've just tried OpenELEC 7.0 beta 2 (with Kodi 16.1 RC) and the problem persists. (Plus the VNSI plugin from OpenELEC's repository doesn't work there due to low API version.)

**Comment by popcornmix** [comment]
Do you have "deinterlace video" set to "auto" or "on"?
I only see the problem with "on".
"auto" would be the recommended setting, otherwise you will be deinterlacing (and so reducing image quality) or progressive video.

**Comment by LubosD** [comment]
I use "on", the problem goes away with "auto". Great!

All TV channels here are interlaced and saving the settings for "all videos" only seems to apply to them to live TV (and not video files), so there was no reason to use "auto".

**Comment by popcornmix** [comment]
Okay, "auto" means we start without deinterlace and enable deinterlace after first video frame is decoded (using aspect ratio and interlaced flags from decoder).
"on" means we start with deinterlace enabled which stops us seeing the aspect ratio from decoder.

I am working on splitting the decoder and deinterlacer, partly to resolve this issue, but also to allow gpu deinterlace with software decoder, so this issue should be resolved in the future.

**Comment by LubosD** [comment]
OK. I will close the issue here. Thanks @FernetMenta for getting me help and thanks @popcornmix for the advice :-)

**Comment by keynet** [comment]
I think I've noted the same or similar issue - the link explains how to reproduce it.
http://forum.kodi.tv/showthread.php?tid=275934&pid=2342698#pid2342698
