### ISSUE TITLE
Unable to build on Arch Linux

### ISSUE THREAD

**Issue by M-Reimer** [kodi-pvr/pvr.vdr.vnsi#87]
I'm trying to build the latest GIT version on Arch Linux. Currently this fails for me.

I use the following build script:
https://github.com/VDR4Arch/vdr4arch/blob/vdr-stable/kodi-addon-pvr-vdr-vnsi/PKGBUILD

The following versions are installed:
p8-platform 2.0.1-2
kodi-platform 20160516.c8188d8-1
kodi 16.1-4

While compiling I get the following:
-- VDR OSD support enabled via OpenGL
-- VDR_VERSION=2.6.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/build
[  8%] Building CXX object CMakeFiles/pvr.vdr.vnsi.dir/src/VNSIData.cpp.o
[ 16%] Building CXX object CMakeFiles/pvr.vdr.vnsi.dir/src/VNSIDemux.cpp.o
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp: In member function 'DemuxPacket\* cVNSIDemux::Read()':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp:152:33: error: 'struct PVR_STREAM_PROPERTIES::PVR_STREAM' has no member named 'iPID'
         if (m_streams.stream[i].iPID == pid)
                                 ^~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp: In member function 'void cVNSIDemux::StreamChange(cResponsePacket_)':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp:307:31: error: 'struct PVR_STREAM_PROPERTIES::PVR_STREAM' has no member named 'iPID'
       m_streams.stream[count].iPID = pid;
                               ^~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp:351:31: error: 'struct PVR_STREAM_PROPERTIES::PVR_STREAM' has no member named 'iSubtitleInfo'
       m_streams.stream[count].iSubtitleInfo = (composition_id & 0xffff) | ((ancillary_id & 0xffff) << 16);
                               ^~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp: In member function 'bool cVNSIDemux::StreamContentInfo(cResponsePacket_)':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp:404:31: error: 'struct PVR_STREAM_PROPERTIES::PVR_STREAM' has no member named 'iPID'
       if (m_streams.stream[i].iPID == pid)
                               ^~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIDemux.cpp:440:16: error: 'struct PVR_STREAM_PROPERTIES::PVR_STREAM' has no member named 'iSubtitleInfo'
         props->iSubtitleInfo = (composition_id & 0xffff) | ((ancillary_id & 0xffff) << 16);
                ^~~~~~~~~~~~~
make[2]: **\* [CMakeFiles/pvr.vdr.vnsi.dir/build.make:255: CMakeFiles/pvr.vdr.vnsi.dir/src/VNSIDemux.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp: In member function 'bool cVNSIData::Start(const string&, int, const char_, const string&)':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:89:8: error: 'class CHelper_libXBMC_pvr' has no member named 'ConnectionStateChange'
   PVR->ConnectionStateChange("VNSI started", PVR_CONNECTION_STATE_CONNECTING, "VNSI started");
        ^~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:89:46: error: 'PVR_CONNECTION_STATE_CONNECTING' was not declared in this scope
   PVR->ConnectionStateChange("VNSI started", PVR_CONNECTION_STATE_CONNECTING, "VNSI started");
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp: In member function 'virtual void cVNSIData::OnDisconnect()':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:100:8: error: 'class CHelper_libXBMC_pvr' has no member named 'ConnectionStateChange'
   PVR->ConnectionStateChange("vnsi connection lost", PVR_CONNECTION_STATE_DISCONNECTED, XBMC->GetLocalizedString(30044));
        ^~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:100:54: error: 'PVR_CONNECTION_STATE_DISCONNECTED' was not declared in this scope
   PVR->ConnectionStateChange("vnsi connection lost", PVR_CONNECTION_STATE_DISCONNECTED, XBMC->GetLocalizedString(30044));
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp: In member function 'virtual void cVNSIData::OnReconnect()':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:107:8: error: 'class CHelper_libXBMC_pvr' has no member named 'ConnectionStateChange'
   PVR->ConnectionStateChange("vnsi connection established", PVR_CONNECTION_STATE_CONNECTED, XBMC->GetLocalizedString(30045));
        ^~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:107:61: error: 'PVR_CONNECTION_STATE_CONNECTED' was not declared in this scope
   PVR->ConnectionStateChange("vnsi connection established", PVR_CONNECTION_STATE_CONNECTED, XBMC->GetLocalizedString(30045));
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp: In member function 'PVR_ERROR cVNSIData::GetRecordingsList(ADDON_HANDLE)':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:790:11: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
       tag.iChannelUid = -1;
           ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:793:13: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
         tag.iChannelUid = uuid;
             ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:796:6: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
  tag.iChannelUid = PVR_RECORDING_CHANNEL_TYPE_TV;
      ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:796:20: error: 'PVR_RECORDING_CHANNEL_TYPE_TV' was not declared in this scope
  tag.iChannelUid = PVR_RECORDING_CHANNEL_TYPE_TV;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:798:6: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
  tag.iChannelUid = PVR_RECORDING_CHANNEL_TYPE_RADIO;
      ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:798:20: error: 'PVR_RECORDING_CHANNEL_TYPE_RADIO' was not declared in this scope
  tag.iChannelUid = PVR_RECORDING_CHANNEL_TYPE_RADIO;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:800:6: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'channelType'; did you mean 'iGenreType'?
  tag.channelType = PVR_RECORDING_CHANNEL_TYPE_UNKNOWN;
      ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:800:20: error: 'PVR_RECORDING_CHANNEL_TYPE_UNKNOWN' was not declared in this scope
  tag.channelType = PVR_RECORDING_CHANNEL_TYPE_UNKNOWN;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:804:11: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
       tag.iChannelUid = PVR_CHANNEL_INVALID_UID;
           ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:804:25: error: 'PVR_CHANNEL_INVALID_UID' was not declared in this scope
       tag.iChannelUid = PVR_CHANNEL_INVALID_UID;
                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:805:11: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'channelType'; did you mean 'iGenreType'?
       tag.channelType = PVR_RECORDING_CHANNEL_TYPE_UNKNOWN;
           ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:805:25: error: 'PVR_RECORDING_CHANNEL_TYPE_UNKNOWN' was not declared in this scope
       tag.channelType = PVR_RECORDING_CHANNEL_TYPE_UNKNOWN;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp: In member function 'PVR_ERROR cVNSIData::GetDeletedRecordingsList(ADDON_HANDLE)':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:955:11: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
       tag.iChannelUid = vresp->extract_S32();
           ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:958:11: error: 'PVR_RECORDING {aka struct PVR_RECORDING}' has no member named 'iChannelUid'; did you mean 'strChannelName'?
       tag.iChannelUid = PVR_CHANNEL_INVALID_UID;
           ^~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:958:25: error: 'PVR_CHANNEL_INVALID_UID' was not declared in this scope
       tag.iChannelUid = PVR_CHANNEL_INVALID_UID;
                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp: In member function 'virtual void_ cVNSIData::Process()':
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:1061:9: error: 'class CHelper_libXBMC_pvr' has no member named 'ConnectionStateChange'
    PVR->ConnectionStateChange("vnsi server not reacheable",
         ^~~~~~~~~~~~~~~~~~~~~
/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/src/VNSIData.cpp:1062:10: error: 'PVR_CONNECTION_STATE_SERVER_UNREACHABLE' was not declared in this scope
          PVR_CONNECTION_STATE_SERVER_UNREACHABLE, nullptr);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: **\* [CMakeFiles/pvr.vdr.vnsi.dir/build.make:231: CMakeFiles/pvr.vdr.vnsi.dir/src/VNSIData.cpp.o] Error 1
make[1]: **\* [CMakeFiles/Makefile2:100: CMakeFiles/pvr.vdr.vnsi.dir/all] Error 2
make: **\* [Makefile:150: all] Error 2

**Comment by FernetMenta** [comment]
You can't compile master for kodi v16. There were lots of api changes in v17. Either compile master with Kodi v17 or checkout branch Jarvis for v16.

**Comment by M-Reimer** [comment]
Thank you for this information. Next problem:
Versions are still the same as mentioned above.

CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findplatform.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "platform",
  but CMake did not find one.

  Could not find a package configuration file provided by "platform" with any
  of the following names:

    platformConfig.cmake
    platform-config.cmake

  Add the installation prefix of "platform" to CMAKE_PREFIX_PATH or set
  "platform_DIR" to a directory containing one of the above files.  If
  "platform" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/build/BUILDDIR/kodi-addon-pvr-vdr-vnsi/src/pvr.vdr.vnsi/build/CMakeFiles/CMakeOutput.log".

**Comment by FernetMenta** [comment]
> Versions are still the same as mentioned above

confused. as mentioned, this won't work

**Comment by M-Reimer** [comment]
I've forgot to mention that I've tried with the latest commit in the "Jarvis" branch. When doing so, I get the above error message.

**Comment by FernetMenta** [comment]
> Could not find a package configuration file provided by "platform" with any

platform was renamed to p8-platform (by pulse eight). seems your system does not have package platform installed.

**Comment by FernetMenta** [comment]
btw: I won't waste any time bothering with Jarvis. v17 in current state is already much much better.

**Comment by M-Reimer** [comment]
As long as v16 is "stable" and shipped by my distribution, I prefer to use that.
At least for me this change (see "prepare") fixes the p8-platform problem. So far, I just did a compile test. Still have to check if the compiled addon is running.
https://github.com/VDR4Arch/vdr4arch/blob/vdr-stable/kodi-addon-pvr-vdr-vnsi/PKGBUILD

**Comment by M-Reimer** [comment]
I'm now running the PVR addon patched the way described in my comment above (sed commands replacing some strings). I think it wouldn't be the worst idea to add this to the repository so the "Jarvis" version can compile against p8-platform and it is not required to have an outdated library. Would you accept a pull request?

**Comment by FernetMenta** [comment]
p8-platform is a set of headers, no library. imo it is wrong to package it and make other projects depend on this package. Nobody has every tested the most recent version of p8-platform with Jarvis version of the addons. A bug fix in p8-platform can easily result in an issue for the applications using it.
I recommend to build the addons the same way as our build servers do. This is by using cmake files in Kodi source tree. This will download the correct version of (p8-)platform into the build environment.

**Comment by M-Reimer** [comment]
At least the Arch Linux package actually contains a library:
https://www.archlinux.org/packages/community/x86_64/p8-platform/files/
And as far as I can see Kodi doesn't depend on "libplatform" at all...

**Comment by FernetMenta** [comment]
right, in the meantime the mess with p8-platform got even bigger. fact is that vnsi does not make use of the binary part of p8-platform and should not be linked with it. this is going to be changed.

our servers build pvr addons with this version of platform:
https://github.com/xbmc/xbmc/blob/Jarvis/project/cmake/addons/depends/common/platform/platform.txt

Hence CMakeLists can't be changed to p8-platform. Jarvis is frozen and there won't be any more changes for it.
