### ISSUE TITLE
Cannot build under 17.0b1 on Debian

### ISSUE THREAD

**Issue by mase76** [kodi-pvr/pvr.vdr.vnsi#88]
Hi!
I cannot build this addon on my Debian Jessie machine with Kodi 17.0b1.

`pvr.vdr.vnsi did not match any of the supported addons.  A list of
  supported addons can be viewed by building the 'supported_addons' target.
  Addon definitions are loaded from ADDONS_DEFINITION_DIR
  (/usr/local/src/xbmc-17.0b1-Krypton/project/cmake/addons/addons).`

**Comment by mase76** [comment]
I had to add these addons to
project/cmake/addons/addons

**Comment by FernetMenta** [comment]
If this folder is empty, it gets created automatically. I struggled with this myself. Hopefully this gets changed in the future.
