### ISSUE TITLE
Constant caching (regression)

### ISSUE THREAD

**Issue by LubosD** [kodi-pvr/pvr.vdr.vnsi#94]
I've moved away from OpenELEC to LibreELEC today which included updating the vnsi plugin. I don't see any versioning here, but OpenELEC used what they called version 1.10.10 of pvr.vdr.vnsi.

After this, switching between TV channels became a lot slower (the "caching" popup appears several times) and occasionally it just [keeps caching forever](https://www.youtube.com/watch?v=42dSRVk4Po0), which is very annoying. The TV is streamed from a powerful local server via Ethernet.

I've tried using OSMC instead, but the same is happening there as well. It used to work just great with an older version of the plugin. (I obviously cannot rule out that there is a problem in Kodi itself.)

**Comment by FernetMenta** [comment]
please pastebin a debug log

**Comment by LubosD** [comment]
Newest OpenELEC doesn't seem to suffer from this -> closing.
